# Generated by Django 5.0.6 on 2024-07-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aviacompany', models.CharField(max_length=100)),
                ('Duration', models.CharField(max_length=10)),
                ('Eating', models.CharField(max_length=20)),
                ('Viza', models.CharField(max_length=50)),
                ('Medical_assistance', models.IntegerField()),
                ('Experienced_highlyeducated', models.CharField(max_length=100)),
                ('Additions', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('langue', models.CharField(max_length=4)),
                ('phone', models.IntegerField()),
                ('telegram', models.CharField(max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
            ],
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
            ],
        ),
    ]
